### ISSUE TITLE
[Improvement] - Add Test Units & Continuous Integration & A Logo

### ISSUE THREAD

**Issue by bauripalash** [cloudlibz/clocal-gcp#19]
* **Test units are a very essential part of a project which is helpful in many ways and most importantly it would help people believe that our program does actually work**

* **I think it would be very useful to add a CI service such as Travis which will make it possible to test the code by running the test units after each push and pull request**

* **Adding a logo has nothing to with the codebase but it makes a good feel and leaves a good impact on users**

**Comment by dilantha111** [comment]
@bauripalash  
Now we have a logo and unit tests. Addressed the CI Support in another issue.
#60
