### ISSUE TITLE
yarn start func start gives an error

### ISSUE THREAD

**Issue by shehand** [cloudlibz/clocal-gcp#79]
When I tried to execute the command "yarn start func start" or "clocal-gcp func start" it gives an error like following.
![screenshot from 2019-02-17 12-31-11](https://user-images.githubusercontent.com/25993584/52909598-4d5c3700-32b1-11e9-96e0-fa6d60c6af5e.png)

I tried the command after "docker login" also. But it gave me the same error.

**Comment by shehand** [comment]
@rehrumesh  this was the issue regarding the missing docker image

**Comment by shalithasuranga** [comment]
Hey @shehand  looks like now image name is updated. Also why not you can build your own image using the Dockerfile :) then edit the image name in js file

**Comment by shehand** [comment]
yeah, @shalithasuranga thanks for the advice XD

**Comment by rehrumesh** [comment]
I am closing this since this is fixed.
